<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml2/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
<link rel='stylesheet' type='text/css' href='http://cmffs.webstract.com.au/css/site.css' />
<link rel='stylesheet' type='text/css' href='http://cmffs.webstract.com.au/css/site_print.css' media="print" />
</head>
<body>
	<table width=100%>
		<tr>
			<td><a id='logo' href='www.flyingfoxstudios.com.au'></a></td>
			<td>Enter Text</td>
		</tr>
		<tr>
			<td id='topbar' colspan=2></td>
		</tr>
		<tr>
			<td colspan=2>
				<table width=100%>
					<tr>
						<td>Enter Text</td>
						<td>Enter Text</td>
					</tr>
					<tr>
						<td>Enter Text</td>
						<td>Enter Text</td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td>Enter Text</td>
			<td>Enter Text</td>
		</tr>
		<tr>
			<td id='botbar' colspan=2></td>
		</tr>
		<tr>
			<td id='footerbar' colspan=2></td>
		</tr>
	</table>
</body>
</html>
