<?php
//////////////////////////////////////////////////////////////////////////////
//                                                                          //
// $Id::                                                                  $ //
//                                                                          //
// Copyright (C) 2006 - Creditworks Australia Pty Ltd                       //
//                                                                          //
// This source code is subject to commerical confidentiality and may not be //
// disclosed to unauthorised thrid parties without written permission from  //
// the management of Creditworks Australia Pty Ltd                          //
//                                                                          //
//////////////////////////////////////////////////////////////////////////////

require_once("../local.inc");
define("ACTION_DEF", "secure");
require_once(PHPLIB_DIR."main.inc");
?>
