<?php

// number of labels on a page
$LABEL_LAYOUT["Across"] = 2; // number of columns
$LABEL_LAYOUT["Down"] = 8; // number of rows

//============================================================
// EVERTHING BELOW IS OPTIONAL
//============================================================

// margin on the outside of the page
//$LABEL_LAYOUT["PageMargins"] = 5; // 5mm of blank space on all sides of the page
$LABEL_LAYOUT["PageMargins"] = array(
	0, // 5mm border on top
	10, // 10mm border on bottom
	3, // 15mm border on left
	3, // 20mm border on right
	);

// margins within each label
//$LABEL_LAYOUT["LabelMargins"] = 5; // 5mm margin on all sides within each label
//$LABEL_LAYOUT["LabelMargins"] = array(
//	5, // 5mm margin at top of label
//	10, // 10mm margin at bottom
//	15, // 15mm margin at left
//	20 // 20mm margin at right
//	);

// paper size
//$LABEL_LAYOUT["PageSize"] = "a4 portrait";

// font name and size
//$LABEL_LAYOUT["FontName"] = "Helvetica";
//$LABEL_LAYOUT["FontSize"] = 10;

?>
